[
    {
        "username": "teonv",
        "password": "iloveyou",
        "fullname": "Nguyễn Văn Tèo",
        "email": "teonv@fpt.edu.vn",
        "gender": "true",
        "birthday": "1995-12-21",
        "money": "1500000",
        "marks": [
            { "Id": "ADAV", "mark": 20 },
            { "Id": "ADBS", "mark": 5 },
            { "Id": "ADTE", "mark": 8 },
            { "Id": "ADUI", "mark": 17 },
            { "Id": "ASNE", "mark": 12 },
            { "Id": "CLCO", "mark": 15 },
            { "Id": "DBAV", "mark": 67 },
            { "Id": "DBBS", "mark": 21 },
            { "Id": "GAME", "mark": 42 },
            { "Id": "HTCS", "mark": 25 },
            { "Id": "INMA", "mark": 28 },
            { "Id": "JAAV", "mark": 47 },
            { "Id": "JABS", "mark": 53 },
            { "Id": "JSPR", "mark": 28 },
            { "Id": "LAYO", "mark": 47 },
            { "Id": "MOWE", "mark": 23 },
            { "Id": "PHPP", "mark": 54 },
            { "Id": "PMAG", "mark": 34 },
            { "Id": "Template", "mark": 70 },
            { "Id": "VBPR", "mark": 62 },
            { "Id": "WEBU", "mark": 12 }
        ]
    },
    {
        "username": "pheonv",
        "password": "iloveyou",
        "fullname": "Nguyễn Văn Chí Phèo",
        "email": "pheonv@fpt.edu.vn",
        "gender": "true",
        "birthday": "1985-10-11",
        "money": "2500000",
        "marks": [
            { "Id": "ADAV", "mark": 9 },
            { "Id": "ADBS", "mark": 23 },
            { "Id": "ADTE", "mark": 12 },
            { "Id": "ADUI", "mark": 4 },
            { "Id": "ASNE", "mark": 80 },
            { "Id": "CLCO", "mark": 15 },
            { "Id": "DBAV", "mark": 80 },
            { "Id": "DBBS", "mark": 22 },
            { "Id": "GAME", "mark": 40 },
            { "Id": "HTCS", "mark": 25 },
            { "Id": "INMA", "mark": 70 },
            { "Id": "JAAV", "mark": 47 },
            { "Id": "JABS", "mark": 53 },
            { "Id": "JSPR", "mark": 24 },
            { "Id": "LAYO", "mark": 62 },
            { "Id": "MOWE", "mark": 42 },
            { "Id": "PHPP", "mark": 43 },
            { "Id": "PMAG", "mark": 6 },
            { "Id": "Template", "mark": 70 },
            { "Id": "VBPR", "mark": 62 },
            { "Id": "WEBU", "mark": 8 }
        ]
    },
    {
        "username": "nopt",
        "password": "iloveyou",
        "fullname": "Phạm Thị Nở",
        "email": "nopt@fpt.edu.vn",
        "gender": "false",
        "birthday": "1993-05-15",
        "money": "2000000",
        "marks": [
            { "Id": "ADAV", "mark": 50 },
            { "Id": "ADBS", "mark": 3 },
            { "Id": "ADTE", "mark": 20 },
            { "Id": "ADUI", "mark": 1 },
            { "Id": "ASNE", "mark": 37 },
            { "Id": "CLCO", "mark": 12 },
            { "Id": "DBAV", "mark": 2 },
            { "Id": "DBBS", "mark": 25 },
            { "Id": "GAME", "mark": 24 },
            { "Id": "HTCS", "mark": 25 },
            { "Id": "INMA", "mark": 68 },
            { "Id": "JAAV", "mark": 72 },
            { "Id": "JABS", "mark": 34 },
            { "Id": "JSPR", "mark": 45 },
            { "Id": "LAYO", "mark": 47 },
            { "Id": "MOWE", "mark": 12 },
            { "Id": "PHPP", "mark": 13 },
            { "Id": "PMAG", "mark": 41 },
            { "Id": "Template", "mark": 70 },
            { "Id": "VBPR", "mark": 6 },
            { "Id": "WEBU", "mark": 16 }
        ]
    }
]